title: CRL Technologies Docs
description: Public documentation hub
theme: jekyll-theme-cayman
lang: en
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
